baseURL = 'https://flockmill.com/'
languageCode = 'en-us'
title = 'Flockmill'
theme = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
resourceDir = "../resources"
enableRobotsTXT = true

#sectionPagesMenu = 'main'
[pagination]
pagerSize = 12

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = "images/logo-white-full@2x.png"
description = "Flockmill"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3

[[params.ananke_socials]]
