baseURL = 'https://flockmill.com/'
languageCode = 'en-us'
title = 'Flockmill'
theme = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
resourceDir = "../resources"
enableRobotsTXT = true

#sectionPagesMenu = 'main'
[pagination]
pagerSize = 12

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = "images/logo-white-full@2x.png"
description = "Flockmill"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3
custom_css = ["/css/custom.css"]

[[params.ananke_socials]]

[[menu.main]]
name = "About Our Community"
url = "/about/"
weight = 1

[[menu.main]]
name = "Some of our efforts"
url = "/efforts/"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 3

[[menu.main]]
name = "Community Links"
url = "/community/"
weight = 4

[[menu.main]]
name = "Owners"
url = "/owners/"
weight = 5

[[menu.main]]
name = "Renters"
url = "/renters/"
weight = 6
